comp_w_1_config:
    type_hint: COMP_W
    config:
        val_0: "some value"

comp_w_2_config:
    type_hint: COMP_W
    config:
        val_0: "some value"        
        
comp_z_config:
    type_hint: COMP_Z
    config:
        val_3: "some other value"
        comp_y_config:
            type_hint: COMP_Y
            config:
                val_2: "yet another value"
                comp_x_config:
                    type_hint: COMP_X
                    config:
                        val_1: "final value"
                comp_w_config:
                    reference_key: "comp_w_1_config"
                    pass_type: by_reference