comp_w_1_config:
    type_hint: COMP_W
    val_0: "some value"
    comp_v_config:
        type_hint: COMP_W
        val_0: "some other value"

comp_w_2_config:
    type_hint: COMP_W
    val_0: "some value"        
        
comp_z_config:
    type_hint: COMP_Z
    val_3: "some other value"
    comp_y_config:
        type_hint: COMP_Y
        val_2: "yet another value"
        comp_x_config:
            type_hint: COMP_X
            val_1: "final value"
        comp_w_config:
            instance_key: "comp_w_1_config"
            pass_type: BY_REFERENCE