hydra:
  output_subdir: null
  run:
    dir: .

data:
  dataset_dir_path: data/datasets/wikitext-103-raw-v1-tokenized
training:
  num_epochs: 30
  process_group_backend: "nccl"
loss:
  target_class: llm_gym.loss_functions.CLMCrossEntropyLoss
  target_subscription_key: target_key
  prediction_subscription_key: logits
runner:
  target_class: llm_gym.fsdp.fsdp_runner.FSDPRunner
  process_group_backend: ${training.process_group_backend}
model:
  target_class: llm_gym.gpt2.gpt2_model.GPT2LLM
  prediction_publication_key: logits
# local_rank: ${oc.env:LOCAL_RANK}
