settings:  
  experiment_id: "abc"
  referencing_keys:
    sample_key: input_ids
    target_key: target_ids
  training:
    callback_interval_in_batches: 6
    global_num_training_samples: 2048
    global_num_seen_samples: 0
    do_apply_activation_checkpointing: true
    gradient_acc_step: 1
    local_train_micro_batch_size: 1
    sequence_length: 256
  cuda_env:
    local_rank: ${modalities_env:LOCAL_RANK}
    global_rank: ${modalities_env:RANK}
    world_size: ${modalities_env:WORLD_SIZE}



collate_fn:  
  component_key: collate_fn
  variant_key: gpt_2_llm_collator
  config:
    sample_key: ${settings.referencing_keys.sample_key}
    target_key: ${settings.referencing_keys.target_key}

train_dataset:
  component_key: dataset
  variant_key: packed_mem_map_dataset_megatron
  config: 
    raw_data_path: /raid/s3/opengptx/max_lue/modalities/data/sample_datasets/redpajama_v2/mem_map/redpajama_v2_llama_2_tokenized_num_samples_1024_train.pbin
    block_size: ${settings.training.sequence_length}
    sample_key: ${settings.referencing_keys.sample_key}

train_dataloader:
  component_key: data_loader
  variant_key: default
  config:
    num_workers: 2
    pin_memory: true
    shuffle: false
    dataloader_tag: "train"
    dataset:
      instance_key: train_dataset
      pass_type: BY_REFERENCE
    batch_sampler:
      component_key: batch_sampler
      variant_key: default
      config:
        batch_size: ${settings.training.local_train_micro_batch_size}
        drop_last: false
        sampler:
          component_key: sampler
          variant_key: distributed_sampler
          config:
            rank: ${settings.cuda_env.global_rank}
            num_replicas: ${settings.cuda_env.world_size}
            shuffle: true
            dataset:
              instance_key: train_dataset
              pass_type: BY_REFERENCE
    collate_fn:
      instance_key: collate_fn
      pass_type: BY_REFERENCE

# OLD 

eval_dataloaders: []

training:
  global_num_training_samples: 2048
  callback_interval_in_samples: 256

checkpointing:
  checkpointing_strategy:
    type_hint: SaveKMostRecentCheckpointsStrategy
    config:
      k: -1   # -1 to save all checkpoints
  checkpointing_execution:
    type_hint: FSDPToDiscCheckpointing
    config: 
      checkpoint_path: ./data/checkpoints
      global_rank: ${oc.env:RANK}

running_env:
  type_hint: FSDPRunningEnv
  config:
    process_group_backend: ${training.process_group_backend}
    local_rank: ${oc.env:LOCAL_RANK}
    mixed_precision_settings: BF_16
    sharding_strategy: FULL_SHARD
    block_names: [LlamaDecoderLayer]

model:
  type_hint: HuggingFacePretrainedModel
  config:
    model_type: AutoModelForCausalLM
    model_name: epfl-llm/meditron-7b
    sample_key: ${data.sample_key}
    prediction_key: logits
    huggingface_prediction_subscription_key: logits
    kwargs: 
      cache_dir: /raid/s3/opengptx/max_lue/hf_cache/

scheduler:
  type_hint: StepLR
  config:
    step_size: 1
    gamma: 0.1

optimizer:
  type_hint: AdamW
  config:
    lr: 0.0001


loss:
  type_hint: CLMCrossEntropyLoss
  config:
    target_key: ${data.target_key}
    prediction_key: ${model.config.prediction_key}